apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}
type: Opaque
data:
  encryptionKey: {{ .Values.secrets.encryptionKey | b64enc }}
  {{- if .Values.database.mongoDb.user }}
  mongoDbUser: {{ .Values.database.mongoDb.user | b64enc }}
  {{- end }}
  {{- if .Values.database.mongoDb.password }}
  mongoDbPassword: {{ .Values.database.mongoDb.password | b64enc }}
  {{- end }}
  {{- if .Values.database.mySql.user }}
  mySqlUser: {{ .Values.database.mySql.user | b64enc }}
  {{- end }}
  {{- if .Values.database.mySql.password }}
  mySqlPassword: {{ .Values.database.mySql.password | b64enc }}
  {{- end }}
  {{- if .Values.database.postgreSql.user }}
  postgreSqlUser: {{ .Values.database.postgreSql.user | b64enc }}
  {{- end }}
  {{- if .Values.database.postgreSql.password }}
  postgreSqlPassword: {{ .Values.database.postgreSql.password | b64enc }}
  {{- end }}
