#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG=$(cat "$1")
BRANCH=$(git rev-parse --abbrev-ref HEAD)
VERSION_REGEXP="^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$"

# shellcheck disable=SC2039
if [[ $BRANCH == main ]] || [[ $BRANCH == master ]]; then
  if [[ $COMMIT_MSG == PATCH:* ]]; then
    VERSION_LEVEL="patch"
  elif [[ $COMMIT_MSG == MINOR:* ]]; then
     VERSION_LEVEL="minor"
  elif [[ $COMMIT_MSG == MAJOR:* ]]; then
    VERSION_LEVEL="minor"
  elif [[ $COMMIT_MSG =~ $VERSION_REGEXP ]]; then
    rm -f .husky/VERSION_LEVEL
    exit 0
  elif [[ $COMMIT_MSG == INTERNAL:* ]]; then
    exit 0
  else
    echo "ERROR: Commit message must start with either 'PATCH:', 'MINOR:' or 'MAJOR:'"
    exit 1
  fi

  echo $VERSION_LEVEL > .husky/VERSION_LEVEL
fi
