#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# shellcheck disable=SC2039
if [[ -f .husky/VERSION_LEVEL ]]; then
  VERSION_LEVEL=$(cat .husky/VERSION_LEVEL)
  NEW_VERSION=$(npm version $VERSION_LEVEL)
  git push origin $NEW_VERSION
fi

